config/routes.rb
Rails.application.routes.draw do

  root "static_pages#root"
  get "/result" => "static_pages#result", as: :result

  namespace :api, defaults: {format: :json} do
    resources :properties, only: [:create, :destroy, :index, :update]
    resources :saved_properties, only: [:create, :destroy, :index, :update]
    resources :photos, only: [:create, :show, :index]
    resource :session, only: [:create, :destroy, :show]
    resources :users, only: [:create, :show]
  end

  namespace :api do
    resources :properties, only: :show
  end

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/_header.html.erb
<div class="app-header group">
  <h1 class="app-logo">CityStreets</h1>
  <ul class="header-list group">
    <% if signed_in? %>
      <li>My Properties</li>
      <li><%= button_to "Sign Out", session_url, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign In", new_session_url, class: "sign-in" %></li>
      <li class="register-link">
        <%= link_to "Register (It's Free)", new_user_url, class: "register" %>
      </li>
      </ul>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CityStreets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDa3AEpGryJpxgWcqJoY4GVUtkIaESIOjk" charset="utf-8"></script>
  <!-- <script src="https://maps.googleapis.com/maps/api/geocode/key=AIzaSyAzXbe85FPmrTNrY3eKx7sH0E01BUHHBos" charset="utf-8"></script> -->
</head>
<body>


<!-- <%= render "layouts/header" %> -->
<%= render "layouts/errors" %>
<%= yield %>

</body>
</html>